# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc ""
  homepage "https://github.com/duckhue01/jwt"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duckhue01/jwt/releases/download/0.1.0/jwt_Darwin_x86_64.tar.gz"
      sha256 "adde014cd5791e1c6522e21b459b49eb3d35a6ad6dc2527f240906c8d7aff3d2"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duckhue01/jwt/releases/download/0.1.0/jwt_Darwin_arm64.tar.gz"
      sha256 "93af170ceb9638e54bcc718b05256152cca8c476c0ab461dee612b1755a29d9b"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duckhue01/jwt/releases/download/0.1.0/jwt_Linux_arm64.tar.gz"
      sha256 "be50089851502b5dcea56d8d70e1f2a581696e7a79bcb59c01ecca3e9c222965"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duckhue01/jwt/releases/download/0.1.0/jwt_Linux_x86_64.tar.gz"
      sha256 "e309dcb827632ed70a0d7c3db09cfc0d1b077cb0723b3ad82bcc8020316bdaaf"

      def install
        bin.install "jwt"
      end
    end
  end
end
